server:
  port: 8080
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ankit-adi/config-server
          clone-on-start: true